@echo off
cd "%userprofile%\desktop"

echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
echo %random% > %random%.virus
